---
abstract: 'Scripting API for the Jack Audio Connection Kit'
author:
  - 'Ed Sweeney <ed@onextent.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: jacks
provides:
  jacks:
    file: lib/jacks.pm
    version: 0
  jacks::JsClient:
    file: lib/jacks.pm
    version: 0
  jacks::JsEvent:
    file: lib/jacks.pm
    version: 0
  jacks::JsPort:
    file: lib/jacks.pm
    version: 0
  jacks::JsPortBuffer:
    file: lib/jacks.pm
    version: 0
  jacksc:
    file: lib/jacks.pm
    version: 0
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: v0.1.1

